import {
  ShieldCheckIcon,
  ExclamationTriangleIcon,
  ClipboardDocumentCheckIcon,
  DocumentTextIcon,
  AcademicCapIcon,
  IdentificationIcon,
  MicrophoneIcon,
  ClockIcon,
  EnvelopeIcon,
  PhoneIcon,
  MapPinIcon,
  BriefcaseIcon,
  ArrowPathIcon,
  ArchiveBoxIcon,
  NewspaperIcon,
  UserGroupIcon,
  GlobeAltIcon,
  LockClosedIcon,
  BoltIcon,
  HeartIcon,
  CodeBracketIcon,
  CpuChipIcon,
  Cog6ToothIcon,
  ChartBarIcon,
  MegaphoneIcon,
} from '@heroicons/react/24/outline';

export const products = [
  {
    id: 'ozlershield',
    name: 'OzlerShield',
    subtitle: 'Workforce Compliance Tracker',
    icon: ShieldCheckIcon,
    color: 'blue',
    tagline: 'Never let an expired credential put your registration at risk again.',
    description: 'Real-time dashboard tracking every worker\'s credentials, screening status, certifications, and training completions. Automated alerts, rostering gates, and continuous audit evidence.',
    trigger: 'Worker screening expiry wave — February 2026 onwards',
    price: '$3–$5 per worker/month',
    features: [
      { title: 'Traffic-Light Dashboard', desc: 'See every worker\'s compliance status at a glance. Green (compliant), amber (expiring soon), red (expired or missing). Filter by credential type, team, location.' },
      { title: 'Automated Expiry Alerts', desc: 'Configurable alerts at 90, 60, 30, and 7 days before any credential expires. Email and SMS notifications to workers and managers.' },
      { title: 'Rostering Compliance Gate', desc: 'Automatically blocks non-compliant workers from being rostered for shifts. Protects providers from accidentally deploying workers with expired credentials.' },
      { title: 'Audit Evidence Export', desc: 'One-click export generates timestamped PDF or Excel evidence packs. Mapped to relevant standards. Always current, never scrambled together the night before.' },
      { title: 'Skill2Care Integration', desc: 'Training completions in Skill2Care automatically update worker credentials in OzlerShield. No manual data entry. No gaps.' },
      { title: 'Multi-Site Management', desc: 'Manage workers across multiple sites, services, and states from a single dashboard. Perfect for providers operating across aged care and NDIS.' },
    ],
    shortDesc: 'Real-time credential monitoring, automated expiry alerts, rostering compliance gates, and audit evidence export.',
  },
  {
    id: 'ozlersirs',
    name: 'OzlerSIRS',
    subtitle: 'Incident Manager',
    icon: ExclamationTriangleIcon,
    color: 'red',
    tagline: 'Meet your 24-hour reporting obligation. Every time.',
    description: 'Mobile-first incident capture, AI-powered triage, countdown timers, investigation tracking, and audit-ready incident registers. Designed for the reality of care work.',
    trigger: 'SIRS 24-hour Priority 1 reporting obligation',
    price: '$150–$600 per facility/month',
    features: [
      { title: '90-Second Incident Capture', desc: 'Structured question flow guides workers through incident reporting in under 90 seconds. Mobile-first design works on any smartphone.' },
      { title: 'AI Triage Engine', desc: 'Suggests incident classification — Priority 1, Priority 2, or non-reportable — based on structured data. AI suggests, human approves.' },
      { title: '24-Hour Countdown Timer', desc: 'Real-time countdown from the moment anyone in the organisation becomes aware. Automated escalation if critical thresholds are reached.' },
      { title: 'Manager Approval Workflow', desc: 'Every classification requires human approval with full audit trail. Timestamped decisions, reviewer identity, reasoning captured.' },
      { title: 'Investigation Tracker', desc: 'Templates for root cause analysis, corrective actions, and preventive measures. Assign tasks, set deadlines, track closure.' },
      { title: 'Audit-Ready Register', desc: 'Complete incident history with all documentation, decisions, timelines, and outcomes. Export-ready for auditors and the NDIS Commission.' },
    ],
    shortDesc: 'Mobile-first capture, AI triage, 24-hour countdown, investigation tracking, and audit-ready incident register.',
  },
  {
    id: 'ozlerready',
    name: 'OzlerReady',
    subtitle: 'Audit Readiness Kit',
    icon: ClipboardDocumentCheckIcon,
    color: 'teal',
    tagline: 'From zero to audit-ready. We prepare you to pass.',
    description: 'End-to-end registration preparation for providers facing their first audit or renewal. Policy generation, gap analysis, evidence pack export.',
    trigger: 'Mandatory NDIS registration — July 2026',
    price: '$1,500–$4,000 one-off',
    features: [
      { title: 'Registration Pathway Wizard', desc: 'Identifies your registration category, audit type, and required standards. Step-by-step guidance from application to approval.' },
      { title: 'Policy Document Generator', desc: 'Auto-generates 4 procedures, 5 processes, and 12 supporting documents tailored to your provider type and service categories.' },
      { title: 'Gap Analysis Dashboard', desc: 'Red/amber/green status per standard outcome. See exactly where you\'re compliant and where you need work.' },
      { title: 'Self-Assessment Builder', desc: 'Pre-filled templates for the Commission portal. Map your evidence to requirements. Submit with confidence.' },
      { title: 'Auditor Evidence Pack', desc: 'One-click export with cover page mapping all documents to relevant standards. Professional, organised, ready for the auditor.' },
      { title: 'AQA Referral Network', desc: 'Connected with approved quality auditors for seamless handoff when you\'re ready for your audit.' },
    ],
    shortDesc: 'Registration wizard, policy generator, gap analysis, and one-click auditor evidence pack.',
  },
  {
    id: 'ozlerpolicy',
    name: 'OzlerPolicy',
    subtitle: 'Standards & Policy Engine',
    icon: DocumentTextIcon,
    color: 'amber',
    tagline: 'Policies that update themselves when regulations change.',
    description: 'Living policy library mapped to every outcome under the Strengthened Quality Standards. Version control, staff acknowledgment tracking, and AI-powered updates.',
    trigger: 'Strengthened Quality Standards — effective November 2025',
    price: '$150/month flat',
    features: [
      { title: 'Living Policy Library', desc: 'Version-controlled policy documents mapped to every outcome across aged care and NDIS standards. Always current, always accessible.' },
      { title: 'Standards-to-Policy Mapping', desc: 'Visual matrix showing which policies address which standard outcomes. Instant gap identification.' },
      { title: 'Staff Acknowledgment Tracking', desc: 'Digital sign-off with timestamps. Know exactly which staff have read and acknowledged each policy.' },
      { title: 'AI Update Engine', desc: 'When standards change, the engine flags affected policies and drafts revisions for human review.' },
      { title: 'Skill2Care Integration', desc: 'Link policies to training modules. When a policy updates, relevant training is flagged for affected workers.' },
      { title: 'Version History & Audit Trail', desc: 'Complete history of every change, who made it, and why. Full transparency for governance and audits.' },
    ],
    shortDesc: 'Living policy library mapped to every outcome, version control, and AI-powered regulatory updates.',
  },
  {
    id: 'Skill2Care',
    name: 'Skill2Care',
    subtitle: 'Training Platform',
    icon: AcademicCapIcon,
    color: 'green',
    tagline: 'Train your workforce. Credentials update automatically.',
    description: 'Non-accredited and accredited training modules for care workers. Mobile-first delivery. Completions feed directly into OzlerShield.',
    trigger: 'Continuous professional development requirements',
    price: '$25–$50 per module or bundled annual',
    features: [
      { title: 'Non-Accredited Modules', desc: 'SIRS awareness, infection control, privacy and dignity, dementia care, manual handling, cultural safety, and more.' },
      { title: 'RTO Partnerships', desc: 'Accredited modules through registered training organisation partnerships. First Aid, Medication Administration, nationally recognised qualifications.' },
      { title: 'Mobile-First Delivery', desc: 'Workers complete training from their phone between shifts. Progress saves automatically. No desktop required.' },
      { title: 'Auto-Credential Updates', desc: 'Complete a module and your credential updates in OzlerShield instantly. No admin intervention.' },
      { title: 'Manager Dashboard', desc: 'Assign modules to teams or individuals. Track completion rates. Identify training gaps before they become compliance issues.' },
      { title: 'Assessment & Certification', desc: 'Built-in assessments validate understanding. Digital certificates issued on completion. Evidence ready for audits.' },
    ],
    shortDesc: 'Non-accredited and accredited modules with auto-credential updates. Mobile-first for workers in the field.',
  },
  {
    id: 'ozlerpass',
    name: 'OzlerPass',
    subtitle: 'Worker Credential Passport',
    icon: IdentificationIcon,
    color: 'blue',
    tagline: 'Your credentials. Your career. One portable profile.',
    description: 'Worker-owned digital credential wallet. Verified screening, training, certifications — shareable with any employer via link or QR code.',
    trigger: 'Cross-sector workforce mobility and screening portability',
    price: 'Free for workers | $4–$5/worker/month for employers',
    features: [
      { title: 'Worker-Owned Profile', desc: 'Credentials belong to the worker, not the employer. When you change jobs, your verified profile comes with you.' },
      { title: 'Verified Credentials', desc: 'Screening numbers, training completions, certifications, First Aid, WWCC, visa status — all verified and timestamped.' },
      { title: 'Instant Sharing', desc: 'Share your complete credential profile via secure link or QR code. Employers verify in seconds, not days.' },
      { title: 'Auto-Population', desc: 'Skill2Care completions and OzlerShield updates automatically reflect in your passport. Always current.' },
      { title: 'Cross-Sector Portability', desc: 'Works across NDIS, aged care, home care, and disability support. One profile for all sectors.' },
      { title: 'Network Effects', desc: 'More workers with passports makes verification more valuable for employers. More employers accepting passports drives worker adoption.' },
    ],
    shortDesc: 'Worker-owned digital wallet with verified credentials. Shareable, portable, instant verification.',
  },
  {
    id: 'ozlerscribe',
    name: 'OzlerScribe',
    subtitle: 'Clinical Documentation AI',
    icon: MicrophoneIcon,
    color: 'teal',
    comingSoon: true,
    tagline: 'Speak for 30 seconds. Get structured clinical notes.',
    description: 'Voice-to-structured-notes engine that transforms verbal shift summaries into properly formatted clinical documentation aligned with NDIS practice standards.',
    trigger: 'NDIS planning framework changes — mid-2026',
    price: 'Pricing TBC — Join the waitlist',
    features: [
      { title: 'Voice Capture', desc: '30-second voice recording from any smartphone. Workers speak naturally about the support they provided.' },
      { title: 'AI Transcription', desc: 'Accurate speech-to-text with support for Australian accents, care terminology, and participant names.' },
      { title: 'Clinical Restructuring', desc: 'Transforms casual language into structured clinical documentation aligned with practice standards.' },
      { title: 'Practice Standards Mapping', desc: 'Notes automatically tagged to relevant NDIS practice standard domains.' },
      { title: 'Plan Reassessment Evidence', desc: 'Properly documented notes support participant evidence at plan reassessment.' },
      { title: 'Full Audit Trail', desc: 'Original voice recording, transcription, and structured output all preserved.' },
    ],
    shortDesc: 'Voice-to-structured-notes, maps to NDIS practice standards terminology.',
  },
];

export const pricingTiers = [
  {
    name: 'Comply',
    price: '$5',
    unit: '/worker/month',
    description: 'Essential compliance tracking for growing providers.',
    cta: 'Get Started',
    ctaStyle: 'btn-secondary',
    features: [
      'OzlerShield — Workforce Compliance Tracker',
      'Automated expiry alerts (90/60/30/7 days)',
      'Rostering compliance gate',
      'Audit evidence export (PDF/Excel)',
      'Email support',
      'Up to 100 workers',
    ],
  },
  {
    name: 'Protect',
    price: '$12',
    unit: '/worker/month',
    description: 'Complete compliance and incident management.',
    cta: 'Book a Demo',
    ctaStyle: 'btn-primary',
    featured: true,
    features: [
      'Everything in Comply',
      'OzlerSIRS — Incident Manager',
      'OzlerPolicy — Standards & Policy Engine',
      'AI triage and 24-hour countdown',
      'Living policy library',
      'Priority email & phone support',
      'Unlimited workers',
    ],
  },
  {
    name: 'Dominate',
    price: '$20',
    unit: '/worker/month',
    description: 'The complete ecosystem with training integration.',
    cta: 'Talk to Sales',
    ctaStyle: 'btn-dark',
    features: [
      'Everything in Protect',
      'OzlerReady — Audit Readiness Kit',
      'Skill2Care integration',
      'OzlerPass — Worker Credential Passport',
      'API access',
      'Dedicated success manager',
      'Custom integrations',
      'SLA guarantee',
    ],
  },
];

export const standaloneProducts = [
  { name: 'OzlerReady', price: '$1,500–$4,000', desc: 'One-off audit preparation package. Registration wizard, policy generator, evidence pack.' },
  { name: 'Skill2Care Modules', price: '$25–$50', desc: 'Per module pricing. Volume discounts available. RTO-accredited modules at partner rates.' },
  { name: 'Enterprise', price: 'Custom', desc: 'For providers with 500+ workers. Custom pricing, dedicated infrastructure, bespoke integrations.' },
];

export const regulatoryTimeline = [
  { date: 'November 2025', status: 'ACTIVE', title: 'Strengthened Aged Care Quality Standards', desc: 'The most detailed quality standards in three decades. Every aged care provider must update their entire policy suite and demonstrate measurable outcomes.' },
  { date: 'December 2022', status: 'ACTIVE', title: 'SIRS Expansion to Home Care', desc: 'Serious Incident Response Scheme now applies to home care providers. Priority 1 incidents require 24-hour reporting with civil penalties for non-compliance.' },
  { date: 'February 2026', status: 'NOW', title: 'Worker Screening Expiry Wave', desc: 'First wave of 5-year NDIS Worker Screening Checks expiring. Rolling renewal crisis across tens of thousands of workers over the next 5 years.' },
  { date: 'April 2026', status: 'UPCOMING', title: 'Quality Auditor Market Disruption', desc: 'Major approved quality auditor exiting NDIS services. Audit pipeline will be congested. Providers should prepare early.' },
  { date: 'July 2026', status: 'UPCOMING', title: 'NDIS Mandatory Platform Registration', desc: 'SIL and platform providers must register by this date or cease operating. Includes audits, suitability checks, and worker screening.' },
  { date: 'Mid-2026', status: 'UPCOMING', title: 'I-CAN v6 Assessment Framework', desc: 'New strengths-based assessment framework. Good documentation supports evidence for participant plans at reassessment.' },
];

export const blogPosts = [
  { slug: 'worker-screening-expiry-guide', title: 'The Worker Screening Expiry Crisis: What Every Provider Needs to Know', tag: 'Compliance', tagColor: 'red', date: 'February 2026', readTime: '8 min', excerpt: 'The first wave of 5-year NDIS Worker Screening Checks is expiring. Here\'s what\'s happening, why it matters, and how to prepare.', icon: ShieldCheckIcon, gradient: 'from-oz-navy to-oz-blue', featured: true },
  { slug: 'ndis-mandatory-registration-guide', title: 'NDIS Mandatory Registration: Your Complete Guide to July 2026', tag: 'Regulation', tagColor: 'blue', date: 'February 2026', readTime: '10 min', excerpt: 'Everything you need to know about the mandatory registration deadline.', icon: ClipboardDocumentCheckIcon, gradient: 'from-oz-teal to-oz-blue' },
  { slug: 'sirs-classification-mistakes', title: 'SIRS Reporting: The 5 Most Common Classification Mistakes', tag: 'SIRS', tagColor: 'red', date: 'January 2026', readTime: '6 min', excerpt: 'Misclassifying incidents is the fastest way to a non-conformance.', icon: ExclamationTriangleIcon, gradient: 'from-red-500 to-amber-500' },
  { slug: 'strengthened-quality-standards', title: "Strengthened Quality Standards: What's Actually Changed", tag: 'Standards', tagColor: 'blue', date: 'January 2026', readTime: '7 min', excerpt: 'A practical breakdown of the new standards and what auditors are looking for.', icon: DocumentTextIcon, gradient: 'from-oz-navy to-slate-700' },
  { slug: 'compliance-first-training-culture', title: 'Building a Compliance-First Training Culture', tag: 'Training', tagColor: 'green', date: 'December 2025', readTime: '5 min', excerpt: 'How forward-thinking providers use targeted training to prevent compliance issues.', icon: AcademicCapIcon, gradient: 'from-green-500 to-oz-teal' },
  { slug: 'portable-worker-credentials', title: 'The Case for Portable Worker Credentials in Australian Care', tag: 'Workforce', tagColor: 'blue', date: 'December 2025', readTime: '6 min', excerpt: 'Why credential portability is the next frontier for Australia\'s care workforce.', icon: IdentificationIcon, gradient: 'from-oz-navy to-oz-blue' },
  { slug: 'ai-decision-support-vs-automation', title: 'AI in Aged Care: Decision Support vs Automation', tag: 'Technology', tagColor: 'amber', date: 'November 2025', readTime: '7 min', excerpt: 'Why we believe AI in care should always be decision support.', icon: BoltIcon, gradient: 'from-amber-500 to-orange-600' },
];

export const stats = [
  { value: '21,000+', label: 'Registered NDIS Providers', context: 'All navigating new quality standards' },
  { value: '110K+', label: 'Workers Needed by 2030', context: 'Driving workforce screening demand' },
  { value: '24hr', label: 'SIRS Reporting Deadline', context: 'For serious incidents — missing it is a breach' },
  { value: '$500K+', label: 'Max Civil Penalty', context: 'For non-compliance with NDIS regulations' },
];

export const testimonials = [
  { text: "We were spending two weeks before every audit pulling spreadsheets together. With OzlerShield, our compliance evidence is always current. It's completely changed how we operate.", name: 'Sarah K.', role: 'Operations Manager, NDIS Provider (Vic)', initials: 'SK' },
  { text: "The SIRS module was a game-changer. Our support workers can report incidents in 90 seconds from their phone. No more lost paper forms, no more missed deadlines.", name: 'Michael R.', role: 'Quality Manager, Aged Care Facility (NSW)', initials: 'MR' },
  { text: "We needed to register for the first time. The Audit-in-a-Box walked us through every step. We passed our first audit without a single non-conformance.", name: 'James P.', role: 'Director, SIL Provider (Qld)', initials: 'JP' },
];

export const partnerTypes = [
  { icon: AcademicCapIcon, title: 'RTO Partners', desc: 'Deliver accredited training modules through Skill2Care. Your RTO maintains course ownership. We provide the platform and customers.', features: ['Access to our growing provider network', 'Digital delivery and assessment platform', 'Auto-credential update on completion', 'Revenue sharing on enrolled students'] },
  { icon: ClipboardDocumentCheckIcon, title: 'Quality Auditor Partners', desc: 'Receive referrals from OzlerReady customers who are audit-ready. We prepare providers — you assess them.', features: ['Referral pipeline of prepared providers', 'Standardised evidence pack format', 'Reduced audit friction and rework', 'Co-marketing opportunities'] },
  { icon: UserGroupIcon, title: 'Consulting Partners', desc: 'Complement your advisory services with Ozler technology. Offer clients continuous compliance monitoring.', features: ['White-label and co-branded options', 'Recurring revenue from client subscriptions', 'Partner portal with client management', 'Training and certification program'] },
  { icon: BoltIcon, title: 'Technology Partners', desc: 'Integrate with Ozler via our API. Rostering, care management, and HR tools can push and pull compliance data.', features: ['RESTful API with documentation', 'Webhook support for real-time events', 'Sandbox environment for development', 'Joint go-to-market programs'] },
];

export const companyValues = [
  { icon: ShieldCheckIcon, title: 'Regulatory-First Design', desc: 'Every feature we build is anchored to a specific regulatory obligation with real consequences. We start with the regulation and work backwards.' },
  { icon: UserGroupIcon, title: 'Human-Controlled AI', desc: 'Our AI capabilities are decision support tools. AI suggests, humans approve. We never automate decisions that carry regulatory consequences.' },
  { icon: GlobeAltIcon, title: 'Built for Australia', desc: 'Purpose-built for Australian legislative frameworks. Not adapted from overseas platforms. Our products map directly to Australian standards.' },
  { icon: LockClosedIcon, title: 'Provider Privacy', desc: 'Your data is your data. We adhere to the Australian Privacy Principles. Data hosted on Australian infrastructure.' },
  { icon: BoltIcon, title: 'Ship Fast, Ship Right', desc: 'Regulatory deadlines don\'t wait. We ship quickly but never cut corners on accuracy.' },
  { icon: HeartIcon, title: 'Care-Centric', desc: 'Behind every compliance requirement is a person receiving care. Better compliance means safer outcomes.' },
];

export const getProduct = (id) => products.find(p => p.id === id);
export const getPost = (slug) => blogPosts.find(p => p.slug === slug);

export const jobOpenings = [
  {
    id: 'software-engineer-intern',
    title: 'Software Engineer Intern',
    type: 'Internship',
    location: 'Melbourne, VIC (Hybrid)',
    department: 'Engineering',
    icon: CodeBracketIcon,
    color: 'blue',
    description: 'Join our engineering team and help build the platforms that power compliance for Australian aged care and NDIS providers. You\'ll work alongside senior engineers on real product features from day one.',
    responsibilities: [
      'Build and ship features across our Next.js front-end and Node.js back-end',
      'Write clean, tested, and well-documented code',
      'Participate in code reviews and agile ceremonies',
      'Collaborate with designers and product managers to translate requirements into technical solutions',
      'Contribute to internal tooling, CI/CD pipelines, and developer experience improvements',
    ],
    requirements: [
      'Currently studying Computer Science, Software Engineering, or a related degree',
      'Familiarity with JavaScript/TypeScript and modern web frameworks (React, Next.js preferred)',
      'Understanding of Git and collaborative development workflows',
      'Eagerness to learn and a genuine interest in building products that matter',
      'Australian work rights required',
    ],
  },
  {
    id: 'ai-solutions-architect',
    title: 'AI Solutions Architect',
    type: 'Full-time',
    location: 'Melbourne, VIC (Hybrid)',
    department: 'AI & Data',
    icon: CpuChipIcon,
    color: 'teal',
    description: 'Design and implement the AI-powered capabilities across our product suite — from OzlerScribe\'s voice-to-documentation engine to intelligent compliance gap analysis. You\'ll own the AI architecture end-to-end.',
    responsibilities: [
      'Architect and deploy LLM-based pipelines for document generation, classification, and analysis',
      'Design retrieval-augmented generation (RAG) systems grounded in Australian regulatory frameworks',
      'Evaluate, fine-tune, and benchmark models for accuracy, latency, and cost',
      'Collaborate with product and compliance teams to ensure AI outputs meet regulatory standards',
      'Establish best practices for prompt engineering, model evaluation, and AI safety',
    ],
    requirements: [
      'Degree in Computer Science, AI/ML, or equivalent practical experience',
      '3+ years experience building production ML/AI systems',
      'Deep hands-on experience with LLMs (OpenAI, Anthropic, or open-source models)',
      'Strong Python skills; experience with LangChain, vector databases, and cloud ML infrastructure',
      'Excellent communication skills — able to translate complex AI concepts for non-technical stakeholders',
      'Australian work rights required',
    ],
  },
  {
    id: 'operations-manager',
    title: 'Operations Manager',
    type: 'Full-time',
    location: 'Melbourne, VIC (On-site / Hybrid)',
    department: 'Operations',
    icon: Cog6ToothIcon,
    color: 'amber',
    description: 'Own the day-to-day operations that keep Ozler Care running smoothly. From customer onboarding workflows to internal processes and vendor management — you\'ll build the operational backbone of a fast-growing RegTech startup.',
    responsibilities: [
      'Design and optimise internal workflows for customer onboarding, support, and renewals',
      'Manage relationships with key vendors, partners, and service providers',
      'Oversee office operations, procurement, and administrative functions',
      'Track operational KPIs and report to leadership on efficiency and bottlenecks',
      'Support HR functions including recruitment coordination and team onboarding',
    ],
    requirements: [
      '3+ years experience in operations, business management, or a similar role',
      'Experience in a startup, SaaS, or technology environment preferred',
      'Excellent organisational skills and attention to detail',
      'Strong written and verbal communication skills',
      'Proficiency with project management and productivity tools (Notion, Slack, Google Workspace)',
      'Australian work rights required',
    ],
  },
  {
    id: 'data-ai-analyst-intern',
    title: 'Data & AI Analyst Intern',
    type: 'Internship',
    location: 'Melbourne, VIC (Hybrid)',
    department: 'AI & Data',
    icon: ChartBarIcon,
    color: 'teal',
    description: 'Help us turn raw data into actionable insights and build the analytical foundations behind our AI-powered compliance products. You\'ll work with real datasets across aged care and NDIS to support smarter decision-making.',
    responsibilities: [
      'Analyse large datasets to identify trends, patterns, and compliance risk indicators',
      'Build dashboards and visualisations to communicate insights to product and leadership teams',
      'Support the AI team with data cleaning, feature engineering, and model evaluation',
      'Research and prototype lightweight ML/NLP models for document classification and anomaly detection',
      'Document data pipelines, methodologies, and findings clearly for technical and non-technical audiences',
    ],
    requirements: [
      'Currently studying Data Science, Statistics, Computer Science, AI/ML, or a related degree',
      'Proficiency in Python (pandas, NumPy, scikit-learn) and SQL',
      'Experience with data visualisation tools (Power BI, Tableau, or Matplotlib/Plotly)',
      'Familiarity with basic machine learning concepts and natural language processing is a plus',
      'Strong analytical thinking and attention to detail',
      'Australian work rights required',
    ],
  },
  {
    id: 'marketing-executive',
    title: 'Marketing Executive',
    type: 'Full-time',
    location: 'Melbourne, VIC (Hybrid)',
    department: 'Marketing',
    icon: MegaphoneIcon,
    color: 'blue',
    description: 'Own and execute Ozler Care\'s online and offline marketing strategy. From digital campaigns and SEO to industry events and print collateral — you\'ll drive brand awareness and lead generation across every channel.',
    responsibilities: [
      'Plan, execute, and optimise digital marketing campaigns across Google Ads, LinkedIn, email, and social media',
      'Develop and manage SEO/SEM strategy to grow organic traffic and inbound leads',
      'Coordinate offline marketing initiatives including industry conferences, trade shows, print materials, and direct mail',
      'Create compelling content — blog posts, case studies, brochures, and landing pages — for both online and offline channels',
      'Track campaign performance with analytics tools, report on ROI, and continuously improve conversion funnels',
    ],
    requirements: [
      '2+ years experience in a marketing role covering both digital and traditional channels',
      'Hands-on experience with Google Ads, Google Analytics, LinkedIn Campaign Manager, and email marketing platforms',
      'Strong copywriting skills with the ability to adapt tone for different audiences and formats',
      'Experience coordinating events, sponsorships, or trade show logistics is a plus',
      'Familiarity with the Australian healthcare, aged care, or GovTech sector is highly regarded',
      'Australian work rights required',
    ],
  },
];
